name: Deploy SAM Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Determine environment based on branch
        id: branch_env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "env=prod" >> $GITHUB_OUTPUT
          else
            echo "env=dev" >> $GITHUB_OUTPUT
          fi

      - name: SAM Build
        run: |
          sam build

      - name: Deploy to AWS (dev/prod)
        run: |
          sam deploy \
            --stack-name s3-event-notification-${{ steps.branch_env.outputs.env }} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
              Environment=${{ steps.branch_env.outputs.env }} \
              EmailSubscriptionParam=${{ secrets.NOTIFICATION_EMAIL }} \
            --config-env ${{ steps.branch_env.outputs.env }} \
            --capabilities CAPABILITY_IAM